# ------------------------------------------------------------
# English language
# ------------------------------------------------------------
[sv]
languageName = "sv"
languageCode = "sv-se"
weight = 2

# ------------------------------------------------------------
# English language
# ------------------------------------------------------------
[en]
languageName = "en"
languageCode = "en-us"
weight = 2

# ------------------------------------------------------------
# French language
# ------------------------------------------------------------
[fr]
languageName = "Fr"
languageCode = "fr-fr"
weight = 3
