# ------------------------------------------------------------
# English language
# ------------------------------------------------------------
[sv]
languageName = "sv"
languageCode = "sv-se"
weight = 1

# ------------------------------------------------------------
# French language
# ------------------------------------------------------------
[fr]
languageName = "Fr"
languageCode = "fr-fr"
weight = 3
