
# ------------------------------------------------------------
# English navigation
# ------------------------------------------------------------
[[main]]
name = "hem"
url = ""
weight = 1

[[main]]
name = "frågor & svar"
url = "faq/"
weight = 2


# Dropdown menu
[[main]]
weight = 4
name = "navigering"
hasChildren = true

  [[main]]

  parent = "navigering"
  name = "Hyreshöjningar // förhandlingar"
  url = "forhandling/"
  weight = 2

  [[main]]
  parent = "navigering"
  name = "Uppsagd"
  url = "uppsagd/"
  weight = 3

  [[main]]
  parent = "navigering"
  name = "Brister"
  url = "brister/"
  weight = 4

  [[main]]
  parent = "navigering"
  name = "Hyreslagen"
  url = "hyreslagen/"
  weight = 5

  [[main]]
  parent = "navigering"
  name = "Privatuthyrningslagen"
  url = "ueb/"
  weight = 6

  [[main]]
  parent = "navigering"
  name = "Viktiga datum"
  url = "viktigadatum/"
  weight = 7

  [[main]]
  parent = "navigering"
  name = "Baskunskaper"
  url = "baskunskaper/"
  weight = 1
